import '../models/customer/customer.dart';
import '../models/product/due_and_scheduled_combo.dart';
import '../models/product/product.dart';
import '../models/tasks/service_grease/service_grease.dart';
import '../models/volume/volume.dart';
import '../scaffold/nav/nav.dart';
import '../smart_dates/smart_dates.dart';
import '../tables/columns/customer/customer_columns.dart';

abstract class LocalizationLabels {
  String smartDateRanges(SmartDates range);
  //Table builder

  String get noFiltersApplied;
  String get clearAllFilters;
  String get select;
  String get before;
  String get after;
  String get minimum;
  String get maximum;
  String get sortAscending;
  String get sortDescending;
  String get clearFilter;

  String get notesAdded;

  String filterCriterion(Enum criterion);
  String longName(CustomerColumn column);
  String shortName(CustomerColumn column);

  // Basic
  String get on;
  String get unknownError;
  String get name;
  String get permissions;
  String get docs;
  String get hasDocumnets;
  String get noDocumnets;
  String get userPreviligesIncludeAccessToOnlyThisDepot;
  String get filters;
  String needForScheduling(DueAndNextCombo combo, {required bool abrv});
  String get show;
  String get selectAll;
  String get filter;
  String get enteredBy;
  String get addCollection;
  String get editCollection;
  String get time;
  String get reorder;
  String get areYouSure;
  String get removeStopUnavailable;
  String get cannotRemoveArrivedWaypoint;
  String get confirmNextStopRemoval;
  String get confirmNextStopReorder;
  String get reorderStopUnavailable;
  String get canNotReorderArrivedWaypoint;
  String get added;
  String get removed;
  String get flag;
  String get arrived;
  String get goToRoute;
  String get allDepots;
  String get depotMustBeCreatedToAddCustomer;
  String get updateAssets;
  String get beta;
  String get pleaseConfirmService;
  String get removeServiceConfirmationToSkip;
  String get allGreaseTrapsPumped;
  String get greaseTrapsNotPumped;
  String get due;
  String products(Products e);
  String get location;
  String get dueDate;
  String get dueDateType;
  // String dueDateTypes(DueDateTypes type);
  // String dueDateTypesDescription(DueDateTypes type);
  String get daysSinceReset;
  String get lastResetDate;
  String get lastManualEdit;
  String get entered;
  String get calculatedFillLevel;
  String get manuallyEditFillLevel;
  String get star;
  String get starred;
  String get locked;
  String get stop;
  String get download;
  // String doubleErrors(VDoubleError error);
  String get unavailable;
  String get enterHeight;
  String get inches;
  String get beforePumping;
  String get afterPumping;
  String get inchesFromTop;
  String get inchesFromBottom;
  String get height;
  String get all;
  String get completePreviousStopsFirst;
  String get settings;
  String get noRecentActivity;
  String get company;
  String get reason;
  String get activity;
  String get waypointNotes;
  String get importContainerAssignments;
  String get last;
  String get summary;
  String get clear;
  String get serviceWindowMustBeAtleastFifteenMinutesLong;
  String get endTime;
  // String weekDay(DayOfWeek day, {required bool abrv});
  String get noStopsAdded;
  String get selectDepot;
  String get loadingCustomers;
  String get loadingRoute;
  String get close;
  String navItem(NavItem item);
  String get resettingServiceContainersWarning;
  String get warningContainersHaveChanged;
  String get enterSkipReason;
  String get logs;
  String get auditLogs;
  String get qty;
  String get totals;
  String get viewAll;
  String get loading;
  String get loadingPlaceholder;
  String get month;
  String get invalid;
  String get vol;
  String get fill;
  String get back;
  String get dataHandling;
  String get change;
  String get showDetails;
  String get keep;
  String get convert;
  String get modifiedBy;
  String get modifiedAt;
  String get changeLog;
  String get completed;
  String get hours;
  String get abbrvHours;
  String get minutes;
  String get abbrvMinutes;
  String get duration;
  String get days;
  String get notAvailableSymbol;
  String get ok;
  String get manager;
  String get contactSupportForBadData;
  String get dismiss;
  String get expected;
  String get residual;
  String get remaining;
  String get at;
  String get locale;
  String get dateFormat;
  String get shortMonthFormat;
  String get timeFormat;
  String get today;
  String get now;
  String get appName;
  String get homeTitle;
  String get edit;
  String get cancel;
  String collected({bool titleCase = true});
  String get delete;
  String get details;
  String get update;
  String get complete;
  String get submit;
  String get next;
  String get add;
  String get archiveSelected;
  String getTextToVerify(String text);
  String get validAddressIsRequired;
  String getDeleteConfirmation(String name);
  String getDeactivateConfirmation(String name);
  String requiredField(String fieldName);
  String getArchiveConfirmation(String name);
  String get create;
  String get reiterFooter;
  String get archiveLabel;
  String get invalidEmailFormat;
  String get invalidPhoneNumberFormat;
  String get invalidIntegerFormat;
  String mustBeGreaterThan(int value);
  String mustBeLessThan(int value);
  String get search;
  String get noEntry;
  String getMinutes(int minutes, {bool showValue = false});
  String get estimatedSuffix;
  String get sortBy;
  String get save;
  String get quantity;
  String get remove;
  String get valueTooHigh;
  String get valueTooLow;
  String get done;
  String get generalInfo;
  String get hyphen;
  String get arrival;
  String get completion;
  String get editOptions;
  String get couldNotLaunchNavigation;
  String get tentative;
  String get actual;
  String get notes;
  String get percentSymbol;
  String get isRequired;
  String get somethingWentWrong;
  String get noSearchResults;
  String getFoundCount(int count);
  String get deactivate;
  String get notAvailable;
  String get startDate;
  String get endDate;
  String get sort;
  String get notSelected;
  String get incomplete;
  String get volume;
  String get noLoggedInUser;
  String get noAuditLogsFound;
  String get disclaimVolumeUnit;
  String get warning;
  String get reset;
  String get type;
  String get noChange;
  String displayDurationDaysHrsMins(Duration duration);
  String get fixed;
  String get yes;
  String get no;
  String get noEmailEntered;
  String get generatePDF;
  String get previewPDF;
  String get noEmailsAdded;
  String get recipients;
  String get duplicateEmail;
  String get enterEmailToAdd;
  String get duplicateId;
  String get total;
  String get comments;
  String get payment;
  String get city;
  String get state;
  String get poundsAbbrv;
  String get needed;
  String get available;
  String get created;
  String get lastLogin;
  String get admin;
  String get billing;
  String get takePhoto;
  String get notAvailableOnDesktop;
  String get found;
  String get canNotBeChangedWhenCloning;
  String get noOtherOptionsAvailable;
  String get totalCapacity;
  String get refresh;
  String get title;
  String get enterTitle;
  String get view;
  String get rename;
  String get browseFiles;
  String maxPdfMbError(int size);
  String selectPdfFile(int size);
  String get addDocumentText;

  // Password Reset
  String get resetYourPassword;
  String get resetPassword;
  String get sendPasswordResetLink;
  String get newPassword;
  String get savePassword;
  String get passwordChanged;
  String get goToLogin;
  String getEmailForPasswordReset(String email);
  String get requestNewPasswordReset;

  // Login
  String get emailHintText;
  String get passwordHintText;
  String get passwordLabelText;
  String get signIn;
  String get passwordResetEmailSent;
  String get resetPasswordDescription;
  String get setPassword;
  String get passwordSet;
  String get tooManyRequests;
  String get missingPassword;
  String get missingEmail;
  String get requestPasswordReset;
  String get requestResetEmail;

  // Auth Errors
  String get invalidEmail;
  String get userNotFound;
  String get userDisabled;
  String get weakPassword;
  String get wrongPassword;
  String get emailAlreadyExists;
  String get invalidActionCode;
  String get expiredActionCode;
  String get generalError;

  // Failure Messages
  String get grpcFailureMessage;
  String get cacheFailureMessage;
  String get defaultFailureMessage;
  String get invalidRouteStatus;
  String get noChangesToSubmitErrorMessage;
  String get sendEmailFailureMessage;
  String get userNotFoundFailureMessage;

  // Not Found Page
  String get notFoundTitle;
  String get notFoundMessage;

  // Avatar Button Options
  String get logoutTitle;

  // Sidebar Menu
  String get routingTitle;
  String get routesTitle;
  String get customersTitle;
  String get inventoryTitle;
  String get vehiclesTitle;
  String get containersTitle;
  String get reportsTitle;
  String get companySettingsTitle;
  String get generalSettingsTitle;
  String get driverRouteSettings;
  String get uploadCompanyLogoText;

  // Users
  String get usersPageTitle;
  String get userDetailsPageTitle;
  String get id;
  String get hireDate;
  String get email;
  String get roles;
  String get selectRoles;
  String get newUser;
  String get addUser;
  String get editUser;
  String get user;
  String get users;
  String get noUsers;
  String get noUserDetails;
  String get missingUserId;
  String get firstName;
  String get lastName;
  String get nameLabel;
  String get customId;
  String get useAddressAsAlternateLocation;
  String get phoneNumber;
  String get userInfo;
  String get atLeastOneRole;
  String get customerNameHintText;
  String get deactivateUser;
  String get userSuccessfullyCreated;
  String get userSuccessfullyUpdated;
  String get resendInvite;
  String get lastActive;
  // String permission(Permission permission);
  String get resendInviteConfirmation;
  String get deactivateUserConfirmation;
  // String userRoleName(Roles role);

  // Customer
  String get serviceInterval;
  String get noServiceWindows;
  String get alwaysMarkImportant;
  String get alwaysMarkedImportant;
  String get noContainersAssigned;
  String get serviceWindow;
  String get serviceWindows;
  String get outOfServiceWindow;
  String get updateAllCustomersButtonText;
  String get updateAllCustomers;
  // String updateAllCustomersToFillRateType(FillRateTypes type);
  String get customer;
  String get addCustomerTitle;
  String get billingId;
  String get entryCode;
  String get locationDetails;
  String get locationNotes;
  String get routeNotes;
  String get addCustomerButtonText;
  String get serviceHistory;
  String get customerDetails;
  String get inactiveSwitchText;
  String get activeSwitchText;
  String get lastService;
  String get nextService;
  String get notScheduled;
  String get neverServiced;
  String get containerRemovedSuccessfully;
  String get containersAddedSuccessfully;
  String get removeContainerConfirmation;
  String get removeContainer;
  String get noCustomersFound;
  String get fillRate;
  String get estimatedAmountOnSite;
  String get mapView;
  String get customerNotFound;
  // String editFillRateWarning(
  // Volume oldValue,
  // Volume newValue,
  // );
  // String keepCurrentFillLevel(Volume currentFillLevel);
  // String recalculateCurrentFillLevel(Volume newFillLevel);
  String get enterNewFillLevel;
  String get editFillRate;
  String get editAmountOnSite;
  String get editWasteDeduction;
  String get oilPrice;
  String get editOilPrice;
  String get depotAssignment;
  String get last5AvgFillRate;
  String get fixedFillRate;
  String get last5Average;
  String get fillLevelDate;
  // String fillRateType(FillRateTypes type);
  String get scheduledRoutes;
  String get noScheduledRoutes;
  String get setUcoLocation;
  String get useAddress;
  String get editServiceNotificationRecipients;
  String get serviceNotification;
  // String getServiceNotificationsText(Product product);
  String get fillLevel;
  String get newFillLevel;
  String get deleteCustomer;
  String get canDeleteCustomerMessage;
  String get deleteCustomerConfirmation;
  String get activeRoutes;
  String get noActiveRoutes;
  String get noOnsiteCapacity;
  String percentFullDisplay(Customer customer);
  String get selectAtLeastOneDepot;
  String get customLastServiceDate;
  String get indexPercent;
  String get editIndexPercent;
  String get deleteDocumentConfirmation;
  String get documents;
  String get noDocumentsFound;
  String get uploadDocument;
  String get renameDocument;
  String get fileMustBePdf;

  //Customer Service Status
  String get active;
  String get inactive;
  String get archived;
  String get percentFull;
  String get estimatedFillLevel;
  String get editFillLevel;
  String get fillLevelExceedsCapacity;

  // Vehicles
  String get vehicles;
  String get selectVehicles;
  String get nextRoute;
  String get nextDate;
  String get addVehicle;
  String get editVehicle;
  String get noVehiclesToDisplay;
  String get vehicleNameFieldLabel;
  String get drivers;
  String get selectDrivers;
  String get driver;
  String get vehicle;
  String get deleteVehicle;
  String get createVehicle;
  String get vehicleSuccessfullyCreated;
  String get vehicleSuccessfullyUpdated;
  String get noDriversToDisplay;
  String get createADriver;
  String get createAVehicle;
  String get decalNumber;

  // Depots
  String get depots;
  String get depot;
  String get selectDepots;
  String get noDepotsToDisplay;
  String get addDepot;
  String get deleteDepot;
  String get createDepot;
  String get editDepot;
  String get depotSuccessfullyCreated;
  String get depotSuccessfullyUpdated;
  String get createADepot;

  // Company
  String get companyName;
  String get noCompanyName;
  String get noPhoneNumber;
  String get noEmail;
  String get companyDetails;
  String get atLeast1DepotIsRequired;
  String get companySuccessfullyUpdated;
  String get editCompany;
  String get noCompanyLogo;
  String get defaultServiceTime;
  String get defaultMeasurementType;
  String get defaultDriver;
  String get defaultVehicle;
  String get defaultDepot;
  String get defaultStartTime;
  String get measurementSystem;
  // String measurementSystemText(SystemOfMeasurement system);
  String get defaultWasteDeduction;
  String get errorLoadingCompany;
  String get routeNotificationEmails;
  String get defaultFillRateType;
  String get applyFillRateTypeToAllCustomers;
  String get selection;
  // String collectionTypes(CollectionType type);
  String get collectionType;
  String get noCompaniesToDisplay;
  String get addCompany;

  // Customers
  // String serviceStatus(ServiceStatuses status);
  String get tags;
  String get noTagsFoundPressEnterToAdd;
  String get typeToAddTag;
  String get customers;
  String get noCustomersToDisplay;
  String get status;
  String get address;
  String get lastServiceDate;
  String get nextServiceDate;
  String get archiveSelectedCustomersConfirmation;
  String get archiveCustomer;
  String get archiveSelectedCustomers;
  String get customerSuccessfullyCreated;
  String get customerSuccessfullyUpdated;
  String get editCustomer;
  String get customerId;
  String get noServiceHistory;
  String get noLocationNotes;
  String get noAssignedContainers;
  String get onsiteCapacity;
  String get addContainers;
  String get newOnsiteCapacity;
  String get customerContainerAssignmentSuccessfullyCreated;
  String get percentFullSymbolHeader;
  String get percentFullSymbol;
  String get history;
  String get newAmountOnSite;
  String get noContainersSelected;
  String get customWasteDeduction;
  String get useCustomWasteDeduction;
  String get displayDefaultWasteDeduction;
  String get wasteDeduction;
  // String volumePerMonth(Volume volume);
  String get ucoLocation;

  // Service Routes
  String get clickToChangeStartAndEndPoint;
  String get unskipConfirmation;
  String get copyRoute;
  String get makeCopy;
  String get copyOf;
  String get markedImportant;
  String get notMarkedImportant;
  String get skippingImportantWaypointWarning;
  String get finishingTripWithIncompleteImportantStopsWarning;
  String get selectVehicle;
  String get selectDriver;
  String get dragStopNumbersToReorder;
  String get serviced;
  // String changeMeasureTypeActionNames(ChangeMeasureTypeAction action);
  // String changeMeasureTypeActionExplanation(ChangeMeasureTypeAction action);
  String get totalFillPercent;
  String get remainingFillPercent;
  String volumeCollected();
  String volumeRemaining();
  String get measurementType;
  String get onlyDriverCanStartTrip;
  String get onlyDriverCanContinueTrip;
  String get unscheduled;
  String get started;
  String get scheduled;
  String get lock;
  String get unlock;
  String get addToRoute;
  String get showOnMap;
  String get unNamedRoute;
  String get newRoute;
  String get editRoute;
  String get general;
  String get addStops;
  String get review;
  String get missingRequiredFields;
  String get atLeastOneStopIsRequired;
  String get date;
  String get startTime;
  String get schedule;
  String get routeSuccessfullyScheduled;
  String get stops;
  String get noRoutesToDisplay;
  String get start;
  String get end;
  String get startLabel;
  String get endLabel;
  String get noDriverAssigned;
  // String waypointStatus(WaypointStatus status);
  String tripStatus(TripStatus status);
  // String skipReasonText(SkipReason status);
  // String measurementTypesName(
  // MeasurementTypes type, {
  // SystemOfMeasurement? system,
  // });
  String get routefilter;
  String get addMoreStops;
  String get noStopsAddedYet;
  String get startDateTime;
  String get endDateTime;
  String get noWaypoints;
  String get holdAndDragToReorder;
  String get reorderStops;
  String get optimize;
  String get routeSuccessfullyOptimized;
  String get optimized;
  String get route;
  String get percentFullOnarrival;
  String get gallonsOnArrival;
  String get routeDetails;
  String get approxGallons;
  String get unschedule;
  String get routeSuccessfullyUnscheduled;
  String get cannotDeleteInProgressRoute;
  String get cannotDeleteCompletedRoute;
  String get deleteRoute;
  String get routeSuccessfullyDeleted;
  String get routeSuccessfullyCloned;
  String get routeCouldNotBeCloned;

  String get stopWasSkipped;
  String get deleteSimpleCollectionConfirmation;
  String get deleteCollectionData;
  String get deleteServicedContainerConfirmation;
  String get isNotAvailableForThisContainer;
  String get startRoute;
  String get continueRoute;
  String get finishRoute;
  String get exitRoute;
  String get collectionData;
  String get enterCollectionData;
  String get enterNotes;
  String get totalCollectedAmount;
  String get totalRemainingAmount;
  String get collectedAmount;
  String get remainingAmount;
  String get collectionEntry;
  String get collectionSaved;
  String get collectionUpdated;
  String get skip;
  String get service;
  String get skipped;
  String volumeUnit({bool abrv = false, bool titleCase = false});
  String volumeValueWithUnit(Volume volume, {bool abrv = false});
  String weightUnit({bool abrv = false});

  String get completePreviousStops;
  String get stopNumber;
  String get scheduledArrivalTime;
  String get serviceHistoryTitle;
  String get estimatedCompletion;
  String get arrive;
  String get collectedAmountGreaterThanCapacity;
  String get remainingAmountGreaterThanCapacity;
  String get noMapAppsFound;
  String get selectAMapApp;
  String get truckIsFull;
  String get exceededLegalHours;
  String get other;
  String get typeHere;
  String get finishRouteReasonDialogSubTitle;
  String get succesMessageForFinishedRoute;
  String get genericFailureMessage;
  String get remainingGallons;
  String get flagged;
  String get showScheduledTimes;
  String get explainSkipReason;
  String get routeSuccessfullyCompleted;
  String get enterFinishRouteReason;
  String get missingFinishRouteReason;
  String get unSkip;
  String get reasonForSkipping;
  String get stopSkipped;
  String get dragAndRelease;
  String get collectedSkipWarning;
  String getNoOnsiteCapacityWarning(String customerName);
  String get completedOn;
  String get scheduledStart;
  String get actualStart;
  String get scheduledEnd;
  String get actualEnd;
  String get pleaseSelectAReason;
  String get pleaseEnterOtherReason;
  String get otherReason;
  String get oil;
  String get waste;
  String get zeroCollection;
  // String getZeroCollectionWarning(Volume totalRemainingAmount);
  String get selectDataHandling;
  String get selectACustomer;
  String get totalPredictedGals;
  String get manifestNumber;
  String get manifestNumberShort;
  // String completedRouteEmailSubject(Trip trip);
  // String completedRouteEmailBody(Trip trip);
  String get customerNotes;
  // String serviceNotificationEmailBody(WaypointModel waypoint);
  // String serviceNotificationEmailSubject(WaypointModel waypoint);
  String get completeWaypointConfirmation;
  String get clickAddToCreateNoteForWaypoint;
  String get simpleCollection;
  String get inProgressRoutes;
  String get totalOilCollected;
  String get noInprogressRoutes;
  String get totalCollected;
  String get locationDisabled;
  String get locationRequired;
  String get enableLocationServices;
  String get continueWithoutLocation;
  String get driverLocationRequired;
  String get flags;
  // String serviceFlag(ServiceFlags flag);
  String get enterContainerHeight;
  // String measurementErrors(MeasurementErrors error);
  String get deleteCollectionsBeforeSkip;
  String get addCollectionsBeforeCompleting;
  String get skipUnavailable;
  String get completeStopUnavailable;
  String get setFlags;
  String get addComment;
  String get addImage;
  String get recordAssigned;
  String get cannotEditCollectionDataAssignedToLoad;
  String get remainingOnSite;
  String get noCollectionData;
  String get noRouteCommentsTitle;
  String get noRouteComments;
  String get routeComments;
  String get noHeightErrorMessage;
  String get arrivedOn;

  // Containers
  String get noContainersToDisplay;
  String get capacity;
  String get container;
  String get containers;
  String get addContainer;
  String get createContainer;
  String get editContainer;
  String get containerSuccessfullyCreated;
  String get containerSuccessfullyUpdated;
  String get noCollection;

  // Location
  String get locationDeniedFailure;
  String get locationDeniedForeverFailure;
  String get locationServiceDisabledFailure;
  String get allowLocationPermission;
  String get permissionDeniedForever;

  // Reports
  String get findCollections;
  String get enterDateRange;
  String get enterStartDate;
  String get enterEndDate;
  String get exportToExcel;
  String get noCollectionsFound;
  String get serviceDate;
  String get weights;
  String get weightsTempDisclosure;
  String get showHideColumns;
  String get completedGPS;
  String get arrivedGPS;
  String get gps;
  String get dateRange;

  // Import
  String get parseResult;
  String get parseError;
  String get noErrors;
  String get rowErrors;
  String get verifyCustomerDetails;
  String get importCSVFile;
  String get dataExportDate;

  // Sales
  String get noRecordsAssignedPrompt;
  String get collectionDate;
  String get sellerName;
  String get contractDetails;
  String get shipmentDetails;
  String records({required bool upperCase});
  String get assignedWeight;
  String get totalAssignments;
  String get assignedRecords;
  String get loadingAssignments;
  String get generateAssignments;
  String get removeAll;
  String get load;
  String get editLoad;
  String get noLoadsAddedYet;
  String get addNewBuyer;
  String get cents;
  String get poNumber;
  String get soNumber;
  String get mode;
  String get netWeight;
  String get weight;
  String get sale;
  String get addLoad;
  String get shipDate;
  String get loads;
  // String loadType(LoadType type);
  String get sales;
  String get pricePerPound;
  String get saleId;
  String get buyer;
  String get newSale;
  String get noSalesToDisplay;
  String get buyerIsRequired;
  String get totalPrice;
  String get editSale;
  String get contractDate;
  String get poundsGreaterThanZero;
  // String saleStatus(OilSaleStatus status);
  String get collectionId;
  String get assigned;

  // Buyer
  String get editBuyer;
  String get addBuyer;
  String get buyers;
  String get showBuyers;
  String get noBuyersToDisplay;
}
